# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_01_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lattitude = QtWidgets.QLineEdit(self.centralwidget)
        self.lattitude.setGeometry(QtCore.QRect(220, 390, 181, 22))
        self.lattitude.setObjectName("lattitude")
        self.longitude = QtWidgets.QLineEdit(self.centralwidget)
        self.longitude.setGeometry(QtCore.QRect(10, 390, 181, 22))
        self.longitude.setObjectName("longitude")
        self.show_image = QtWidgets.QPushButton(self.centralwidget)
        self.show_image.setGeometry(QtCore.QRect(30, 490, 93, 28))
        self.show_image.setObjectName("show_image")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(10, 10, 881, 341))
        self.image.setText("")
        self.image.setObjectName("image")
        self.spn = QtWidgets.QLineEdit(self.centralwidget)
        self.spn.setGeometry(QtCore.QRect(10, 450, 181, 22))
        self.spn.setObjectName("spn")
        self.api_longitude = QtWidgets.QLabel(self.centralwidget)
        self.api_longitude.setGeometry(QtCore.QRect(10, 360, 181, 16))
        self.api_longitude.setObjectName("api_longitude")
        self.api_lattitude = QtWidgets.QLabel(self.centralwidget)
        self.api_lattitude.setGeometry(QtCore.QRect(220, 360, 181, 16))
        self.api_lattitude.setObjectName("api_lattitude")
        self.api_type_maps = QtWidgets.QLabel(self.centralwidget)
        self.api_type_maps.setGeometry(QtCore.QRect(220, 420, 181, 16))
        self.api_type_maps.setObjectName("api_type_maps")
        self.api_spn = QtWidgets.QLabel(self.centralwidget)
        self.api_spn.setGeometry(QtCore.QRect(10, 420, 181, 16))
        self.api_spn.setObjectName("api_spn")
        self.type_maps = QtWidgets.QComboBox(self.centralwidget)
        self.type_maps.setGeometry(QtCore.QRect(220, 450, 181, 22))
        self.type_maps.setObjectName("type_maps")
        self.type_maps.addItem("")
        self.type_maps.addItem("")
        self.type_maps.addItem("")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Task_1"))
        self.lattitude.setText(_translate("MainWindow", "55.703118"))
        self.longitude.setText(_translate("MainWindow", "37.530887"))
        self.show_image.setText(_translate("MainWindow", "Ввод"))
        self.spn.setText(_translate("MainWindow", "0.002"))
        self.api_longitude.setText(_translate("MainWindow", "Долгота"))
        self.api_lattitude.setText(_translate("MainWindow", "Широта"))
        self.api_type_maps.setText(_translate("MainWindow", "Вид карты"))
        self.api_spn.setText(_translate("MainWindow", "Масштаб"))
        self.type_maps.setItemText(0, _translate("MainWindow", "map"))
        self.type_maps.setItemText(1, _translate("MainWindow", "sat"))
        self.type_maps.setItemText(2, _translate("MainWindow", "sat.skl"))
